services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - shared

networks:
  shared:
    external: true
